<?xml version="1.0"?>
<!DOCTYPE script PUBLIC
	"-//Apache Software Foundation//Tapestry Script Specification 3.0//EN"
	"http://jakarta.apache.org/tapestry/dtd/Script_3_0.dtd">
<script>

<input-symbol key="message" required="yes"/>
<input-symbol key="target" required="yes"/>
<initialization>
dojo.connect(dojo.byId('${target}'),'onclick', function(e){
	if(confirm(decodeURL('${message}'))
	){}
	else{
		dojo.stopEvent(e);
	}
});
</initialization>

</script>
