<?xml version="1.0" encoding="UTF-8"?>
<definitions name="AsyncProvider" xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://tmaxsoft.com"
    targetNamespace="http://tmaxsoft.com">
    <types>
        <xsd:schema elementFormDefault="qualified"
            targetNamespace="http://tmaxsoft.com"
            xmlns="http://www.w3.org/2001/XMLSchema">
            <complexType name="hello">
                <sequence>
                    <element name="arg0" type="xsd:string" />
                </sequence>
            </complexType>
            <complexType name="helloResponse">
                <sequence>
                    <element name="return" type="xsd:string" />
                </sequence>
            </complexType>
            <element name="hello" type="tns:hello" />
            <element name="helloResponse" type="tns:helloResponse" />
        </xsd:schema>
    </types>
    <message name="hello">
        <part name="parameter" element="tns:hello" />
    </message>
    <message name="helloResponse">
        <part name="parameter" element="tns:helloResponse" />
    </message>
    <portType name="Hello">
        <operation name="hello">
            <input message="tns:hello" />
            <output message="tns:helloResponse" />
        </operation>
    </portType>
    <binding name="HelloBinding" type="tns:Hello">
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <operation name="hello">
            <soap:operation soapAction="asyncprovider" />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
        </operation>
    </binding>
    <service name="Hello">
        <port name="HelloAsyncPort" binding="tns:HelloBinding">
            <soap:address location="REPLACE_WITH_ACTUAL_URL" />
        </port>
    </service>
</definitions>
