#!/bin/sh
# $Id: jeusadmin 20068 2007-05-29 09:07:33Z bluewolf $

# set up JEUS_HOME.
if [ -z "$JEUS_HOME" ] ; then
   PRG="$0"
   progname=`basename "$0"`
   saveddir=`pwd`

   dirname_prg=`dirname "$PRG"`
   cd "$dirname_prg"

   while [ -h "$PRG" ] ; do
      ls=`ls -ld "$PRG"`
      link=`expr "$ls" : '.*-> \(.*\)$'`
      if expr "$link" : '/.*' > /dev/null; then
      PRG="$link"
      else
        PRG=`dirname "$PRG"`"/$link"
      fi
   done

   JEUS_HOME=`dirname "$PRG"`/..

   cd "$saveddir"

   JEUS_HOME=`cd "$JEUS_HOME" && pwd`

fi

. ${JEUS_HOME}/bin/jeus.properties


# set remote debugging (JPDA)
#export VM_OPTION="${VM_OPTION} -agentlib:jdwp=transport=dt_socket,server=y,address=5006,suspend=n"

java $VM_OPTION -classpath ${JEUS_HOME}/lib/system/bootstrap.jar ${TOOL_OPTION}        \
     -Djava.endorsed.dirs=${JEUS_HOME}/lib/endorsed \
     -Djava.library.path=${JEUS_HOME}/lib/system \
     -Djava.naming.factory.initial=jeus.jndi.JEUSContextFactory          \
     -Djava.naming.factory.url.pkgs=jeus.jndi.jns.url                    \
     -Djava.util.logging.config.file=${JEUS_HOME}/bin/logging.properties \
     -Djeus.home=${JEUS_HOME}                                            \
     -Djeus.baseport=${JEUS_BASEPORT}                                    \
     ${JAVA_ARGS}                                                        \
     jeus.server.Bootstrapper \
	 jeus.server.manager.JeusCommander $*
