#!/bin/sh
# $Id: jeus 20068 2007-05-29 09:07:33Z bluewolf $

# set up JEUS_HOME.
if [ -z "$JEUS_HOME" ] ; then
   PRG="$0"
   progname=`basename "$0"`
   saveddir=`pwd`

   dirname_prg=`dirname "$PRG"`
   cd "$dirname_prg"

   while [ -h "$PRG" ] ; do
      ls=`ls -ld "$PRG"`
      link=`expr "$ls" : '.*-> \(.*\)$'`
      if expr "$link" : '/.*' > /dev/null; then
      PRG="$link"
      else
        PRG=`dirname "$PRG"`"/$link"
      fi
   done

   JEUS_HOME=`dirname "$PRG"`/..

   cd "$saveddir"

   JEUS_HOME=`cd "$JEUS_HOME" && pwd`

fi

. ${JEUS_HOME}/bin/jeus.properties

echo "***************************************************************"
echo "  - JEUS Home         : ${JEUS_HOME}                           "
echo "  - JEUS Base Port    : ${JEUS_BASEPORT}                       "
echo "  - Java Vendor       : ${JAVA_VENDOR}                         "
echo "  - Added Java Option : ${JAVA_ARGS}                           "
echo "***************************************************************"

if [ ! -z "${USERNAME}" ]
then
    BOOT_PARAMETER="-U${USERNAME} -P${PASSWORD}"
fi

java $VM_OPTION  $SESSION_MEM \
    -Xbootclasspath/p:${JEUS_HOME}/lib/system/extension.jar  \
    -classpath ${JEUS_HOME}/lib/system/bootstrap.jar \
    -Djava.library.path=${JEUS_HOME}/lib/system \
    -Djava.naming.factory.initial=jeus.jndi.JNSContextFactory \
    -Djava.naming.factory.url.pkgs=jeus.jndi.jns.url \
    -Djava.util.logging.config.file=${JEUS_HOME}/bin/logging.properties \
    -Djeus.jvm.version=${VM_TYPE} \
    -Djeus.home=${JEUS_HOME} \
    -Djeus.session.version=${SESSION_VERSION} \
    -Djeus.baseport=${JEUS_BASEPORT} \
    -Djeus.ejb.checkTable=false \
    -Djeus.ejb.csi.defaultUser=jeus \
    -Djeus.ejb.enable.configDeleteOption=true \
    -Djeus.app.compiler.mode=batch \
    -Djeus.application.keepgenerated=true \
    -Djeus.net.lib=JAVA \
    -Djeus.tm.checkReg=true \
    -Djeus.tm.forcedReg=true \
    -Dcts.interop=true \
    -Djeus.jms.session.tx.checkTransacted=false \
    -Djeus.properties.replicate=jeus,java.util.logging \
    -Djeus.tool.webadmin.locale.language=${JEUS_LANG} \
    -Djava.endorsed.dirs=${JEUS_HOME}/lib/endorsed \
    ${JAVA_ARGS} \
    jeus.server.JeusBootstrapper ${BOOT_PARAMETER} $*
