#!/bin/sh

if [ -z "$JEUS_HOME" ] ; then
   PRG="$0"
   progname=`basename "$0"`
   saveddir=`pwd`

   dirname_prg=`dirname "$PRG"`
   cd "$dirname_prg"

   while [ -h "$PRG" ] ; do
      ls=`ls -ld "$PRG"`
      link=`expr "$ls" : '.*-> \(.*\)$'`
      if expr "$link" : '/.*' > /dev/null; then
      PRG="$link"
      else
        PRG=`dirname "$PRG"`"/$link"
      fi
   done

   JEUS_HOME=`dirname "$PRG"`/..

   cd "$saveddir"

   JEUS_HOME=`cd "$JEUS_HOME" && pwd`

fi

SERVLET_HOME=$JEUS_HOME/webhome/servlet_home

java -classpath ${JEUS_HOME}/lib/system/bootstrap.jar -Djeus.home=${JEUS_HOME} -Djava.naming.factory.initial=jeus.jndi.JNSContextFactory -Djava.naming.factory.url.pkgs=jeus.jndi.jns.url -Djava.library.path=${JEUS_HOME}/lib/system -Djeus.servlethome=${SERVLET_HOME} jeus.server.Bootstrapper jeus.servlet.jsp.compiler.batch.BatchCompiler $*
