#!/bin/sh
# $Id$

# set up JEUS_HOME.
if [ -z "$JEUS_HOME" ] ; then
   PRG="$0"
   progname=`basename "$0"`
   saveddir=`pwd`

   dirname_prg=`dirname "$PRG"`
   cd "$dirname_prg"

   while [ -h "$PRG" ] ; do
      ls=`ls -ld "$PRG"`
      link=`expr "$ls" : '.*-> \(.*\)$'`
      if expr "$link" : '/.*' > /dev/null; then
      PRG="$link"
      else
        PRG=`dirname "$PRG"`"/$link"
      fi
   done

   JEUS_HOME=`dirname "$PRG"`/..

   cd "$saveddir"

   JEUS_HOME=`cd "$JEUS_HOME" && pwd`

fi

. ${JEUS_HOME}/bin/jeus.properties


BOOT_PARAMETER=$*

${JAVA_HOME}/bin/java -classpath ${BOOTSTRAP_CLASSPATH} ${TOOL_OPTION}   \
     -Djeus.home=${JEUS_HOME}                                            \
     -Djeus.baseport=${JEUS_BASEPORT}                                    \
     -Djava.naming.factory.initial=jeus.jndi.JEUSContextFactory          \
     -Djava.naming.factory.url.pkgs=jeus.jndi.jns.url                    \
     -Djava.util.logging.config.file=${JEUS_HOME}/bin/logging.properties \
     ${JAVA_ARGS}                                                        \
     ${BOOTSTRAPPER}                                                     \
	  com.tmax.axis.utils.tcpmon ${BOOT_PARAMETER}