#!/bin/sh
JEUS_HOME=
if [ -z "$JEUS_HOME" ] ; then
   PRG="$0"
   progname=`basename "$0"`
   saveddir=`pwd`

   dirname_prg=`dirname "$PRG"`
   cd "$dirname_prg"

   while [ -h "$PRG" ] ; do
      ls=`ls -ld "$PRG"`
      link=`expr "$ls" : '.*-> \(.*\)$'`
      if expr "$link" : '/.*' > /dev/null; then
      PRG="$link"
      else
        PRG=`dirname "$PRG"`"/$link"
      fi
   done

   JEUS_HOME=`dirname "$PRG"`/..

   cd "$saveddir"

   JEUS_HOME=`cd "$JEUS_HOME" && pwd`

fi

export EJB_HOME=${JEUS_HOME}/webhome/ejb_home
export SERVLET_HOME=${JEUS_HOME}/webhome/servlet_home
export CLIENT_HOME=${JEUS_HOME}/webhome/client_home
export JEUS_BASEPORT=9736

java -classpath ${JEUS_HOME}/lib/system/bootstrap.jar -Djeus.home=${JEUS_HOME} "-Djava.library.path=${JEUS_HOME}/lib/system" -Djava.naming.factory.initial=jeus.jndi.JNSContextFactory -Djava.naming.factory.url.pkgs=jeus.jndi.jns.url "-Djeus.baseport=${JEUS_BASEPORT}" jeus.server.Bootstrapper jeus.servlet.admin.WebAdmin $*
