#!/bin/sh
# $Id$

# set up JEUS_HOME.
if [ -z "$JEUS_HOME" ] ; then
   PRG="$0"
   progname=`basename "$0"`
   saveddir=`pwd`

   dirname_prg=`dirname "$PRG"`
   cd "$dirname_prg"

   while [ -h "$PRG" ] ; do
      ls=`ls -ld "$PRG"`
      link=`expr "$ls" : '.*-> \(.*\)$'`
      if expr "$link" : '/.*' > /dev/null; then
      PRG="$link"
      else
        PRG=`dirname "$PRG"`"/$link"
      fi
   done

   JEUS_HOME=`dirname "$PRG"`/..

   cd "$saveddir"

   JEUS_HOME=`cd "$JEUS_HOME" && pwd`

fi

. ${JEUS_HOME}/bin/jeus.properties


BOOT_PARAMETER=$*

${JAVA_HOME}/bin/java ${WSGEN_OPTS} ${TOOL_OPTION} -cp ${JAVA_HOME}/lib/tools.jar:${JEUS_HOME}/lib/system/javaee.jar:${JEUS_HOME}/lib/system/jaxws-tools.jar:${JEUS_HOME}/lib/system/jeus.jar:${JEUS_HOME}/lib/system/jeus-ws.jar:${JEUS_HOME}/lib/system/jeusapi.jar:${JEUS_HOME}/lib/system/jeusjaxb.jar:${JEUS_HOME}/lib/system/jeusutil.jar:${JEUS_HOME}/lib/system/xml_resource.jar jeus.webservices.jaxws.tools.WsGen ${BOOT_PARAMETER}
