#!/bin/sh
# $Id$

# set up JEUS_HOME.
if [ -z "$JEUS_HOME" ] ; then
   PRG="$0"
   progname=`basename "$0"`
   saveddir=`pwd`

   dirname_prg=`dirname "$PRG"`
   cd "$dirname_prg"

   while [ -h "$PRG" ] ; do
      ls=`ls -ld "$PRG"`
      link=`expr "$ls" : '.*-> \(.*\)$'`
      if expr "$link" : '/.*' > /dev/null; then
      PRG="$link"
      else
        PRG=`dirname "$PRG"`"/$link"
      fi
   done

   JEUS_HOME=`dirname "$PRG"`/..

   cd "$saveddir"

   JEUS_HOME=`cd "$JEUS_HOME" && pwd`

fi

. ${JEUS_HOME}/bin/jeus.properties


BOOT_PARAMETER=$*

XJC_OPTS=

CP="${JEUS_HOME}/lib/system/jaxb-xjc.jar:${JEUS_HOME}/lib/system/javaee.jar:${JEUS_HOME}/lib/system/activation.jar"

${JAVA_HOME}/bin/java ${XJC_OPTS} ${TOOL_OPTION} -classpath ${CP} com.sun.tools.xjc.XJCFacade ${BOOT_PARAMETER}
